"""cascadEE

Revision ID: 11d6abd07e05
Revises: 4b049222f546
Create Date: 2024-12-07 16:30:05.965423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d6abd07e05'
down_revision = '4b049222f546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('chat_messages_chat_room_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_rooms', ['chat_room_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_constraint('chat_rooms_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_rooms_project_id_fkey', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_messages_chat_room_id_fkey', 'chat_rooms', ['chat_room_id'], ['id'])

    # ### end Alembic commands ###
