"""not null

Revision ID: 1ca9f9d6e17a
Revises: 576fb6b14585
Create Date: 2024-11-14 16:14:20.555284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca9f9d6e17a'
down_revision = '576fb6b14585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('responsible_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('responsible_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
