"""defss

Revision ID: 287be927bd75
Revises: 1c1d823d3377
Create Date: 2024-10-27 19:41:52.329117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287be927bd75'
down_revision = '1c1d823d3377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
