"""cascadEE

Revision ID: 4b049222f546
Revises: 4977a08156d5
Create Date: 2024-12-07 16:27:30.337910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b049222f546'
down_revision = '4977a08156d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_executors', schema=None) as batch_op:
        batch_op.drop_constraint('project_executors_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('project_executors_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_executors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_executors_project_id_fkey', 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key('project_executors_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
