"""nullable

Revision ID: 54304cf7ff4a
Revises: eb72cc968ac6
Create Date: 2024-10-27 19:51:26.988286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54304cf7ff4a'
down_revision = 'eb72cc968ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)

    # ### end Alembic commands ###
