"""not null

Revision ID: 576fb6b14585
Revises: bb68bed0c27f
Create Date: 2024-11-14 15:45:50.542425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576fb6b14585'
down_revision = 'bb68bed0c27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)

    # ### end Alembic commands ###
