"""nullable

Revision ID: eb72cc968ac6
Revises: 287be927bd75
Create Date: 2024-10-27 19:50:41.876541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb72cc968ac6'
down_revision = '287be927bd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
        batch_op.alter_column('date_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)

    # ### end Alembic commands ###
