name: PythonMagick

on:
  push:
    branches:
      - gitactions

  pull_request:
    branches:
      - gitactions

jobs:
  super_check:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint isort ruff black pyink

      - name: Run flake8
        continue-on-error: true
        run: |
          flake8 app/routes.py

      - name: Run pylint
        continue-on-error: true
        run: |
          pylint $(git ls-files '*.py')

      - name: Run isort
        continue-on-error: true
        run: |
          isort app/routes.py --check --profile black

      - name: Run ruff
        continue-on-error: true
        run: |
          ruff check app/routes.py

      - name: Run black
        continue-on-error: true
        run: |
          black app/routes.py --check

      - name: Run pyink
        continue-on-error: true
        run: |
          pyink app/routes.py --check
